### PR TITLE
Fix incorrect parsing of Using node's Static property

### LINKED ISSUE #176: Using.Static should convert from nullable bool
Convert should be changed:

``` C#
public sealed class Using
{
    public bool? Static => Convert<bool?>(Attribute());
    //                                 ^
}
```

### PR DESCRIPTION
**Pull request by CptWesley**
Closes #176

### CODE REVIEW

File: src/DotNetProjectFile.Analyzers/MsBuild/Using.cs [hunk 1]
```diff
@@ -7,9 +7,9 @@ public sealed class Using(XElement element, Node parent, MsBuildProject project)
 
     public string? Alias => Attribute();
 
-    public bool? Static => Convert<bool>(Attribute());
+    public bool? Static => Convert<bool?>(Attribute());
 
-    public UsingType Type => (Static, Alias) switch
+    public UsingType Type => (Static ?? false, Alias) switch
```
Comment (Corniel) [inline src/DotNetProjectFile.Analyzers/MsBuild/Using.cs:12]: Maybe define the last one as `_ =>` and put in comment that it is `(true, _)`?

**Review by Corniel — APPROVED** [review]
Besides remark, LGTM

**Review by Corniel — APPROVED** [review]
LGTM!
