### PR TITLE
Match highest SDK First

### LINKED ISSUE #625: Proj0049 Advises C#10 for .NET 10.0.101 SDK
Something obviously goes wrong here:

``` xml
<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>library</OutputType>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>
  
</Project>
````

And the warning
> Use <LangVersion>10</LangVersion> supported by the .NET 10.0.101 SDK

is produced.

### PR DESCRIPTION
**Pull request by Corniel**
Closes #625

### CODE REVIEW

File: src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/PreferLatestLanguageVersion.cs [hunk 1]
```diff
@@ -27,18 +27,18 @@ protected override void Register(ProjectFileAnalysisContext<MsBuildProject> cont
 
     private static LanguageVersion CSharp(SdkVersion sdk) => sdk switch
     {
+        _ when sdk >= SdkVersion.NET10 => LanguageVersion.CS14,
+        _ when sdk >= SdkVersion.NET9 => LanguageVersion.CS13,
         _ when sdk >= SdkVersion.NET6 => LanguageVersion.CS10,
```
Comment (Sjaaky) [inline src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/PreferLatestLanguageVersion.cs]: Why is NET6 still above 8 and 7?
